[package]
name = "imgdd"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "btm"
path = "src/bin/main.rs"
doc = false

[dependencies]
bk-tree = "0.4.0"
img_hash = "3.2.0"
itertools = "0.10"
thiserror = "1.0.30"
triple_accel = "0.4.0"
walkdir = "2.3.2"
